In [8]:
import pandas as pd

In [9]:
main_path = r"C:\Users\NahianSiddique\OneDrive - Blend 360\Hilton\Analytical Projects\HGV 2022 VIP Analysis\Data"

dataset1 = pd.read_excel(f"{main_path}/Model Sample/DMC_TS_Sales_Sample_21_22_20221206.xlsx")
dataset2 = pd.read_excel(f"{main_path}/Model Sample/No_Buy_No_VIP_Sample_21_22_20221205.xlsx")
dataset3 = pd.read_excel(f"{main_path}/Model Sample/VIP_Contracts_Sample_21_22_20221205.xlsx")
print(dataset1.shape)

(24119, 395)

In [10]:
dataset1['source'] = '1'
dataset2['source'] = '2'
dataset3['source'] = '3'

In [11]:
# for i in dataset1.columns:
#     print(i)

In [12]:
full_data = pd.concat([dataset1, dataset2, dataset3])

In [13]:
full_data = full_data.drop(
    columns=[
        "lead_id",
        "t0_baseline_date",
        "full_tour_id",
    ]
)

In [14]:
full_data

,daydiff_since_first_pkg,daydiff_since_last_pkg,prior_all_pkgs,prior_3y_pkgs,prior_1y_pkgs,sum_all_pkg_price,sum_3y_pkg_price,sum_1y_pkg_price,daydiff_since_first_tour,daydiff_since_last_tour,...,slide_any,vids_HGV_duration,vids_ELARA_duration,link_HGV_club_duration,link_any_duration,slide_HCC_duration,slide_unknown_duration,slide_resort_photo_collection_duration,slide_any_duration,source
0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2758.0,1833.0,2,0,0,644.34,NaN,NaN,2269.0,1625.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22274,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
22275,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
22276,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
22277,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
22278,591.0,591.0,1,1,0,168.94,168.94,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [15]:
full_data.to_excel("appended_file.xlsx", index=False)
print("THE END")

THE END