### Importing Vyper

In [1]:
from vyper.user import Model
import pandas as pd
from sklearn.utils import shuffle

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

### Reading in Data

In [2]:
df=pd.read_csv("../source_datasets/Profile America Response Model Data.csv")
df = shuffle(df, random_state = 26)
df_oob = df.iloc[-5000:]
df = df.iloc[:-5000]
print(df_oob.shape, df.shape)

(5000, 104) (59081, 104)

### Creating Model

In [ ]:
Model?

In [3]:
m = Model(data=df, 
          dependent_variable='y',
          training_percentage=0.75, 
          na_drop_threshold=0.5,
          model_type='logistic')

In [4]:
%%time
#string_threshold: when data type is string and if no. of values increase this threshlod the variable is excluded
m.auto_define_variables(categorical_threshold = 100,
                        string_threshold = 100,
                        overwrite=True)

Wall time: 1.32 s

### Model Variable Functions

In [5]:
m.variables.show_types()

{'ID': 'continuous',
 'FIRST_NAME': 'exclude',
 'LAST_NAME': 'exclude',
 'ADDRESS': 'exclude',
 'CITY': 'exclude',
 'STATE': 'categorical',
 'ZIP': 'continuous',
 'CREDIT_CARD_REVOLVERS': 'exclude',
 'CREDIT_SCORE_INDEX': 'categorical',
 'INCOME': 'continuous',
 'HOMEOWNER': 'binary',
 'LOR': 'continuous',
 'MOBILITY_TRIGGER': 'binary',
 'PRESENCE_OF_CHILDREN': 'binary',
 'PRESENCE_OF_CREDIT_CARD': 'exclude',
 'PRESENCE_OF_FINANCE_LOAN': 'binary',
 'PROFITABILITY_INDEX': 'continuous',
 'DWELLING_TYPE': 'continuous',
 'MARITAL_STATUS': 'continuous',
 'AGE_RANGES': 'categorical',
 'NUMBER_OF_CHILDREN': 'exclude',
 'AUTO_INDEX': 'continuous',
 'LIFE_EVENT_INDEX': 'continuous',
 'HOME_VALUE': 'categorical',
 'Childrens Age 0-2': 'exclude',
 'Childrens Age 11-15': 'exclude',
 'Childrens Age 16-17': 'exclude',
 'Childrens Age 3-5': 'exclude',
 'Childrens Age 6-10': 'exclude',
 'Devotional': 'exclude',
 'Reading': 'exclude',
 'Childrens Books': 'exclude',
 'Cooking': 'exclude',
 'Fashion': 'exclude',
 'Interior Decorating': 'exclude',
 'Romance': 'exclude',
 'Baking': 'exclude',
 'Career Advancement Courses': 'exclude',
 'Cigar Smoking': 'exclude',
 'Sweepstakes': 'exclude',
 'Crafts': 'exclude',
 'Cultural/Arts Events': 'exclude',
 'Gardening': 'exclude',
 'Gourmet Foods': 'exclude',
 'DIY': 'exclude',
 'Home Study Courses': 'exclude',
 'Motorcycle Riding': 'exclude',
 'Photography': 'exclude',
 'Quilting': 'exclude',
 'Scrapbooking': 'exclude',
 'Self-Improvement Courses': 'exclude',
 'Sewing/Knitting': 'exclude',
 'Wine': 'exclude',
 'Woodworking': 'exclude',
 'Christian or Gospel': 'exclude',
 'Classical': 'exclude',
 'Country': 'exclude',
 'Jazz': 'exclude',
 'R&B': 'exclude',
 'Rock N Roll': 'exclude',
 'Own a Cat': 'exclude',
 'Own a Dog': 'exclude',
 'Boating/Sailing': 'exclude',
 'Camping/Hiking': 'exclude',
 'Cycling': 'exclude',
 'Fishing': 'exclude',
 'Fitness/Exercise': 'exclude',
 'Golf': 'exclude',
 'Hunting/Shooting': 'exclude',
 'NASCAR': 'exclude',
 'Running': 'exclude',
 'Skiing': 'exclude',
 'Walking for Health': 'exclude',
 'Yoga/Pilates': 'exclude',
 'Casino Gambling': 'exclude',
 'Cruise Ship Vacation': 'exclude',
 'International Travel': 'exclude',
 'Leisure Travel': 'exclude',
 'RV Vacations': 'exclude',
 'Timeshare': 'exclude',
 'Travel within US': 'exclude',
 'Traveler': 'exclude',
 'Net Assets': 'categorical',
 'Interest in Investing': 'exclude',
 'Interest in Mutual Funds': 'exclude',
 'LOYALTY_MEMBERS': 'binary',
 'PERSONAL_TRAVELER': 'binary',
 'VACATION_SPENDERS': 'binary',
 'AIRLINE_UPGRADERS': 'binary',
 'BARGAIN_SHOPPERS': 'binary',
 'interest to purchase Medicare Supplement Insurance': 'exclude',
 'interest to purchase Medicare Advantage Plan': 'exclude',
 'Online Shopper': 'binary',
 'Online Household': 'exclude',
 'Online Insurance Purchasers': 'binary',
 'Subscribes to Magazines Online': 'binary',
 'Online Savings': 'binary',
 'Online Transactor': 'binary',
 'Online Movie Interest': 'binary',
 'Online Music Interest': 'binary',
 'spendperorder': 'continuous',
 'orderspercustomer': 'continuous',
 'spendpercustomers': 'continuous',
 'y': 'target_variable'}

In [6]:
m.variables.get_active_variables()

{'AGE_RANGES',
 'AIRLINE_UPGRADERS',
 'AUTO_INDEX',
 'BARGAIN_SHOPPERS',
 'CREDIT_SCORE_INDEX',
 'DWELLING_TYPE',
 'HOMEOWNER',
 'HOME_VALUE',
 'ID',
 'INCOME',
 'LIFE_EVENT_INDEX',
 'LOR',
 'LOYALTY_MEMBERS',
 'MARITAL_STATUS',
 'MOBILITY_TRIGGER',
 'Net Assets',
 'Online Insurance Purchasers',
 'Online Movie Interest',
 'Online Music Interest',
 'Online Savings',
 'Online Shopper',
 'Online Transactor',
 'PERSONAL_TRAVELER',
 'PRESENCE_OF_CHILDREN',
 'PRESENCE_OF_FINANCE_LOAN',
 'PROFITABILITY_INDEX',
 'STATE',
 'Subscribes to Magazines Online',
 'VACATION_SPENDERS',
 'ZIP',
 'orderspercustomer',
 'spendpercustomers',
 'spendperorder'}

In [7]:
m.variables.get_numeric_variables()

{'AUTO_INDEX',
 'DWELLING_TYPE',
 'ID',
 'INCOME',
 'LIFE_EVENT_INDEX',
 'LOR',
 'MARITAL_STATUS',
 'PROFITABILITY_INDEX',
 'ZIP',
 'orderspercustomer',
 'spendpercustomers',
 'spendperorder'}

In [8]:
m.variables.get_categorical_variables()

{'AGE_RANGES', 'CREDIT_SCORE_INDEX', 'HOME_VALUE', 'Net Assets', 'STATE'}

In [9]:
m.variables.get_binary_variables()

{'AIRLINE_UPGRADERS',
 'BARGAIN_SHOPPERS',
 'HOMEOWNER',
 'LOYALTY_MEMBERS',
 'MOBILITY_TRIGGER',
 'Online Insurance Purchasers',
 'Online Movie Interest',
 'Online Music Interest',
 'Online Savings',
 'Online Shopper',
 'Online Transactor',
 'PERSONAL_TRAVELER',
 'PRESENCE_OF_CHILDREN',
 'PRESENCE_OF_FINANCE_LOAN',
 'Subscribes to Magazines Online',
 'VACATION_SPENDERS'}

### Custom Set Variables

In [10]:
m.set_variable_types({
    'ID': 'exclude', 
    'ZIP': 'exclude', 
    'STATE': 'exclude',
    'AUTO_INDEX': 'exclude',
    'y': 'target_variable'})
m.variables.show_types()

{'ID': 'exclude',
 'FIRST_NAME': 'exclude',
 'LAST_NAME': 'exclude',
 'ADDRESS': 'exclude',
 'CITY': 'exclude',
 'STATE': 'exclude',
 'ZIP': 'exclude',
 'CREDIT_CARD_REVOLVERS': 'exclude',
 'CREDIT_SCORE_INDEX': 'categorical',
 'INCOME': 'continuous',
 'HOMEOWNER': 'binary',
 'LOR': 'continuous',
 'MOBILITY_TRIGGER': 'binary',
 'PRESENCE_OF_CHILDREN': 'binary',
 'PRESENCE_OF_CREDIT_CARD': 'exclude',
 'PRESENCE_OF_FINANCE_LOAN': 'binary',
 'PROFITABILITY_INDEX': 'continuous',
 'DWELLING_TYPE': 'continuous',
 'MARITAL_STATUS': 'continuous',
 'AGE_RANGES': 'categorical',
 'NUMBER_OF_CHILDREN': 'exclude',
 'AUTO_INDEX': 'exclude',
 'LIFE_EVENT_INDEX': 'continuous',
 'HOME_VALUE': 'categorical',
 'Childrens Age 0-2': 'exclude',
 'Childrens Age 11-15': 'exclude',
 'Childrens Age 16-17': 'exclude',
 'Childrens Age 3-5': 'exclude',
 'Childrens Age 6-10': 'exclude',
 'Devotional': 'exclude',
 'Reading': 'exclude',
 'Childrens Books': 'exclude',
 'Cooking': 'exclude',
 'Fashion': 'exclude',
 'Interior Decorating': 'exclude',
 'Romance': 'exclude',
 'Baking': 'exclude',
 'Career Advancement Courses': 'exclude',
 'Cigar Smoking': 'exclude',
 'Sweepstakes': 'exclude',
 'Crafts': 'exclude',
 'Cultural/Arts Events': 'exclude',
 'Gardening': 'exclude',
 'Gourmet Foods': 'exclude',
 'DIY': 'exclude',
 'Home Study Courses': 'exclude',
 'Motorcycle Riding': 'exclude',
 'Photography': 'exclude',
 'Quilting': 'exclude',
 'Scrapbooking': 'exclude',
 'Self-Improvement Courses': 'exclude',
 'Sewing/Knitting': 'exclude',
 'Wine': 'exclude',
 'Woodworking': 'exclude',
 'Christian or Gospel': 'exclude',
 'Classical': 'exclude',
 'Country': 'exclude',
 'Jazz': 'exclude',
 'R&B': 'exclude',
 'Rock N Roll': 'exclude',
 'Own a Cat': 'exclude',
 'Own a Dog': 'exclude',
 'Boating/Sailing': 'exclude',
 'Camping/Hiking': 'exclude',
 'Cycling': 'exclude',
 'Fishing': 'exclude',
 'Fitness/Exercise': 'exclude',
 'Golf': 'exclude',
 'Hunting/Shooting': 'exclude',
 'NASCAR': 'exclude',
 'Running': 'exclude',
 'Skiing': 'exclude',
 'Walking for Health': 'exclude',
 'Yoga/Pilates': 'exclude',
 'Casino Gambling': 'exclude',
 'Cruise Ship Vacation': 'exclude',
 'International Travel': 'exclude',
 'Leisure Travel': 'exclude',
 'RV Vacations': 'exclude',
 'Timeshare': 'exclude',
 'Travel within US': 'exclude',
 'Traveler': 'exclude',
 'Net Assets': 'categorical',
 'Interest in Investing': 'exclude',
 'Interest in Mutual Funds': 'exclude',
 'LOYALTY_MEMBERS': 'binary',
 'PERSONAL_TRAVELER': 'binary',
 'VACATION_SPENDERS': 'binary',
 'AIRLINE_UPGRADERS': 'binary',
 'BARGAIN_SHOPPERS': 'binary',
 'interest to purchase Medicare Supplement Insurance': 'exclude',
 'interest to purchase Medicare Advantage Plan': 'exclude',
 'Online Shopper': 'binary',
 'Online Household': 'exclude',
 'Online Insurance Purchasers': 'binary',
 'Subscribes to Magazines Online': 'binary',
 'Online Savings': 'binary',
 'Online Transactor': 'binary',
 'Online Movie Interest': 'binary',
 'Online Music Interest': 'binary',
 'spendperorder': 'continuous',
 'orderspercustomer': 'continuous',
 'spendpercustomers': 'continuous',
 'y': 'target_variable'}

### Variable Profiling

In [11]:
from vyper.user.explorer import DataProfiler
from openpyxl import Workbook
l = list(m.variables.get_active_variables())# to look at only active variables
l = l + ['y']
var_prof_df = DataProfiler(df[l], dependent_variable='y')
wb = Workbook()
var_prof_df.create_var_profiling_ws(wb=wb, sheet_name='profile', sort_by_variance = 'desc')
wb.save(r"variable profiles logistic.xlsx")

### TNI

In [ ]:
m.tni_smart?

In [12]:
%%time
m.tni_smart(transformations=('Log', 'Pw2'))

Wall time: 3.46 s

In [ ]:
m.tni_transform?

In [13]:
%%time
m.tni_transform()

Wall time: 2.04 s

### Variable Reduction

In [ ]:
?m.variable_reduction

In [14]:
%%time
m.variable_reduction(cluster_type='hclust',
                           wt_corr_dv=1,
                           wt_univ_reg=1,
                           wt_inf_val=1,
                           wt_clust=1,
                           selection = 100)

Wall time: 3.89 s

In [15]:
len(m.var_selected)

80

In [16]:
m.var_selected

['DWELLING_TYPE_TnI_processed',
 'DWELLING_TYPE_bi_(-inf_1.0]',
 'AGE_RANGES_bi_(5.0_6.0]',
 'AIRLINE_UPGRADERS_N',
 'INCOME_TnI_log',
 'orderspercustomer_bi_(11.4708249496982_12.7638888888889]',
 'MARITAL_STATUS_bi_(-inf_1.0]',
 'MARITAL_STATUS_TnI_pw2',
 'spendpercustomers_TnI_log',
 'AGE_RANGES_bi_(7.0_inf]',
 'PROFITABILITY_INDEX_TnI_processed',
 'LIFE_EVENT_INDEX_TnI_pw2',
 'BARGAIN_SHOPPERS_N',
 'AGE_RANGES_bi_(1.0_2.0]',
 'Online Movie Interest_N',
 'PROFITABILITY_INDEX_bi_(-inf_1.0]',
 'INCOME_TnI_processed',
 'Net Assets_bi_(6.0_inf]',
 'spendperorder_TnI_log',
 'orderspercustomer_TnI_processed',
 'spendpercustomers_bi_(873.209509803922_1575.24369863014]',
 'PRESENCE_OF_CHILDREN_N',
 'orderspercustomer_TnI_pw2',
 'HOME_VALUE_bi_(13.0_inf]',
 'LOR_TnI_pw2',
 'DWELLING_TYPE_bi_(1.0_5.0]',
 'LIFE_EVENT_INDEX_TnI_processed',
 'MOBILITY_TRIGGER_N',
 'PROFITABILITY_INDEX_TnI_pw2',
 'spendpercustomers_TnI_pw2',
 'AGE_RANGES_bi_(6.0_7.0]',
 'DWELLING_TYPE_TnI_log',
 'PROFITABILITY_INDEX_TnI_log',
 'LIFE_EVENT_INDEX_bi_(8.0_9.0]',
 'spendperorder_bi_(158.066037735849_170.423795875568]',
 'orderspercustomer_bi_(6.427184466019419_10.264285714285698]',
 'Online Music Interest_N',
 'PRESENCE_OF_FINANCE_LOAN_N',
 'HOME_VALUE_bi_(10.0_11.0]',
 'Subscribes to Magazines Online_N',
 'PROFITABILITY_INDEX_bi_(5.0_10.0]',
 'Online Savings_N',
 'LOR_bi_(3.0_11.0]',
 'spendpercustomers_TnI_processed',
 'Online Transactor_N',
 'LOYALTY_MEMBERS_N',
 'MARITAL_STATUS_TnI_log',
 'HOMEOWNER_N',
 'spendperorder_TnI_pw2',
 'spendpercustomers_bi_(1575.24369863014_1767.10101579325]',
 'HOME_VALUE_tni_assign',
 'INCOME_bi_(-inf_7]',
 'AGE_RANGES_tni_assign',
 'Net Assets_tni_assign',
 'LIFE_EVENT_INDEX_TnI_log',
 'LIFE_EVENT_INDEX_bi_nan',
 'HOME_VALUE_bi_(7.0_8.0]',
 'orderspercustomer_bi_(13.8482858058315_18.7478991596639]',
 'orderspercustomer_TnI_log',
 'LOR_TnI_processed',
 'CREDIT_SCORE_INDEX_tni_assign',
 'VACATION_SPENDERS_N',
 'Online Shopper_N',
 'LOR_bi_(11.0_20.0]',
 'HOME_VALUE_bi_(12.0_13.0]',
 'CREDIT_SCORE_INDEX_bi_(8.0_inf]',
 'MARITAL_STATUS_TnI_processed',
 'orderspercustomer_bi_(10.264285714285698_11.4708249496982]',
 'AGE_RANGES_bi_(-inf_1.0]',
 'MARITAL_STATUS_bi_(1.0_3.0]',
 'Net Assets_bi_(2.0_3.0]',
 'spendperorder_TnI_processed',
 'DWELLING_TYPE_TnI_pw2',
 'PERSONAL_TRAVELER_N',
 'Online Insurance Purchasers_N',
 'AGE_RANGES_bi_(3.0_4.0]',
 'LIFE_EVENT_INDEX_bi_(3.0_5.0]',
 'LOR_TnI_log',
 'INCOME_TnI_pw2',
 'CREDIT_SCORE_INDEX_bi_(5.0_6.0]']

In [17]:
#Combining var_scores and variable_reduction_method_values
m.variable_reduction_method_values.merge(m.var_scores, on = ['variable'], how='left').to_csv('logistic_variable_reduction_output.csv')
m.variable_reduction_method_values.merge(m.var_scores, on = ['variable'], how='left').sort_values(['variable'])

,corr_dv_x,variable,corr_direction,univ_reg_x,inf_val_x,cluster,cluster_correlation,corr_dv_y,univ_reg_y,inf_val_y,clust,selected
68,0.000956,AGE_RANGES_bi_(-inf_1.0],0,0.521409,0.024814,24,0.939841,1,1,1,1,1
13,0.001001,AGE_RANGES_bi_(1.0_2.0],0,0.526341,0.024398,26,0.707107,1,1,1,1,1
75,0.000315,AGE_RANGES_bi_(3.0_4.0],0,0.514790,0.007133,20,1.064611,1,1,1,1,1
2,0.000341,AGE_RANGES_bi_(5.0_6.0],1,0.482199,0.006846,36,0.707107,1,1,1,1,1
30,0.000474,AGE_RANGES_bi_(6.0_7.0],1,0.481457,0.009265,33,0.707107,1,1,1,1,1
9,0.001635,AGE_RANGES_bi_(7.0_inf],1,0.471928,0.028766,16,0.000000,1,1,1,1,1
52,0.003902,AGE_RANGES_tni_assign,1,0.417736,0.088440,54,0.000000,1,1,1,1,1
3,0.002014,AIRLINE_UPGRADERS_N,0,0.551324,0.042322,74,0.000000,1,1,1,1,1
12,0.002628,BARGAIN_SHOPPERS_N,1,0.460540,0.077511,65,0.000000,1,1,1,1,1
79,0.000405,CREDIT_SCORE_INDEX_bi_(5.0_6.0],0,0.516432,0.009318,34,1.101489,1,1,1,1,1
65,0.000592,CREDIT_SCORE_INDEX_bi_(8.0_inf],1,0.473482,0.012100,55,1.140242,1,1,1,1,1
60,0.001858,CREDIT_SCORE_INDEX_tni_assign,1,0.452332,0.057796,63,0.707107,1,1,1,1,1
31,0.018622,DWELLING_TYPE_TnI_log,1,0.321059,0.576729,9,0.000000,1,1,1,1,1
0,0.012082,DWELLING_TYPE_TnI_processed,1,0.321059,0.576729,7,0.000000,1,1,1,1,1
72,0.006850,DWELLING_TYPE_TnI_pw2,1,0.321059,0.576729,8,1.153086,1,1,1,1,1
1,0.025605,DWELLING_TYPE_bi_(-inf_1.0],0,0.681370,0.574532,57,0.000000,1,1,1,1,1
25,0.019409,DWELLING_TYPE_bi_(1.0_5.0],1,0.345545,0.394862,10,0.707107,1,1,1,1,1
47,0.020143,HOMEOWNER_N,1,0.340598,0.425098,6,0.000000,1,1,1,1,1
38,0.002539,HOME_VALUE_bi_(10.0_11.0],0,0.541376,0.070712,25,0.707107,1,1,1,1,1
64,0.000510,HOME_VALUE_bi_(12.0_13.0],0,0.519462,0.011755,12,0.707107,1,1,1,1,1
23,0.020673,HOME_VALUE_bi_(13.0_inf],1,0.340623,0.421615,5,0.000000,1,1,1,1,1
56,0.003178,HOME_VALUE_bi_(7.0_8.0],0,0.546716,0.092417,19,0.707107,1,1,1,1,1
50,0.013173,HOME_VALUE_tni_assign,1,0.321459,0.480586,62,0.707107,1,1,1,1,1
4,0.000217,INCOME_TnI_log,1,0.483133,0.023372,56,0.000000,1,1,1,1,1
16,0.000190,INCOME_TnI_processed,1,0.483133,0.023372,56,0.707107,1,1,1,1,1
78,0.000164,INCOME_TnI_pw2,1,0.483133,0.023372,56,1.148637,1,1,1,1,1
51,0.000355,INCOME_bi_(-inf_7],0,0.518049,0.007894,35,0.707107,1,1,1,1,1
54,0.000332,LIFE_EVENT_INDEX_TnI_log,1,0.497183,0.109037,70,0.710369,1,1,1,1,1
26,0.000122,LIFE_EVENT_INDEX_TnI_processed,1,0.497183,0.109037,69,0.000000,1,1,1,1,1
11,0.000019,LIFE_EVENT_INDEX_TnI_pw2,1,0.497183,0.109037,68,0.707107,1,1,1,1,1
76,0.000111,LIFE_EVENT_INDEX_bi_(3.0_5.0],0,0.508432,0.002437,32,1.126790,1,1,1,1,1
33,0.000449,LIFE_EVENT_INDEX_bi_(8.0_9.0],0,0.522919,0.009767,13,0.707107,1,1,1,1,1
55,0.005195,LIFE_EVENT_INDEX_bi_nan,1,0.446667,0.084655,17,0.000000,1,1,1,1,1
77,0.012233,LOR_TnI_log,0,0.643528,0.302435,43,1.050965,1,1,1,1,1
59,0.008351,LOR_TnI_processed,0,0.643528,0.302435,41,0.659186,1,1,1,1,1
24,0.006503,LOR_TnI_pw2,0,0.643528,0.302435,40,0.707107,1,1,1,1,1
63,0.004903,LOR_bi_(11.0_20.0],0,0.569160,0.132795,42,0.707107,1,1,1,1,1
42,0.000561,LOR_bi_(3.0_11.0],0,0.524600,0.012421,37,0.707107,1,1,1,1,1
45,0.000019,LOYALTY_MEMBERS_N,0,0.504613,0.000392,75,0.707107,1,1,1,1,1
46,0.005226,MARITAL_STATUS_TnI_log,1,0.408860,0.145847,3,0.630474,1,1,1,1,1
66,0.004795,MARITAL_STATUS_TnI_processed,1,0.408860,0.145847,2,1.132645,1,1,1,1,1
7,0.004060,MARITAL_STATUS_TnI_pw2,1,0.408860,0.145847,1,0.000000,1,1,1,1,1
6,0.005719,MARITAL_STATUS_bi_(-inf_1.0],0,0.586500,0.121988,58,0.000000,1,1,1,1,1
69,0.002783,MARITAL_STATUS_bi_(1.0_3.0],1,0.440414,0.057310,4,1.150330,1,1,1,1,1
27,0.003770,MOBILITY_TRIGGER_N,0,0.555653,0.068096,71,1.084893,1,1,1,1,1
70,0.000384,Net Assets_bi_(2.0_3.0],0,0.517033,0.008728,31,0.746481,1,1,1,1,1
17,0.001575,Net Assets_bi_(6.0_inf],1,0.464398,0.029673,18,0.707107,1,1,1,1,1
53,0.002827,Net Assets_tni_assign,1,0.436284,0.075035,53,1.049305,1,1,1,1,1
74,0.000150,Online Insurance Purchasers_N,0,0.513003,0.003102,60,1.152220,1,1,1,1,1
14,0.000090,Online Movie Interest_N,0,0.510834,0.001883,72,0.707107,1,1,1,1,1
36,0.000145,Online Music Interest_N,0,0.513821,0.003058,73,0.707107,1,1,1,1,1
41,0.000175,Online Savings_N,0,0.514550,0.003618,59,0.707107,1,1,1,1,1
62,0.000015,Online Shopper_N,1,0.496806,0.000330,67,0.707107,1,1,1,1,1
44,0.000179,Online Transactor_N,0,0.513954,0.003679,61,0.000000,1,1,1,1,1
73,0.000077,PERSONAL_TRAVELER_N,0,0.509418,0.001590,76,1.154695,1,1,1,1,1
21,0.000542,PRESENCE_OF_CHILDREN_N,1,0.486050,0.013760,64,0.707107,1,1,1,1,1
37,0.003268,PRESENCE_OF_FINANCE_LOAN_N,1,0.452799,0.095987,66,0.707107,1,1,1,1,1
32,0.000085,PROFITABILITY_INDEX_TnI_log,0,0.519838,0.096324,30,0.000000,1,1,1,1,1
10,0.000696,PROFITABILITY_INDEX_TnI_processed,0,0.519838,0.096324,27,0.000000,1,1,1,1,1
28,0.001431,PROFITABILITY_INDEX_TnI_pw2,0,0.519838,0.096324,28,0.707107,1,1,1,1,1
15,0.000262,PROFITABILITY_INDEX_bi_(-inf_1.0],0,0.515241,0.005787,11,0.000000,1,1,1,1,1
40,0.001564,PROFITABILITY_INDEX_bi_(5.0_10.0],0,0.534445,0.039167,29,0.000000,1,1,1,1,1
39,0.002867,Subscribes to Magazines Online_N,0,0.560178,0.058694,78,0.707107,1,1,1,1,1
61,0.000151,VACATION_SPENDERS_N,0,0.514073,0.003171,77,1.064857,1,1,1,1,1
58,0.015964,orderspercustomer_TnI_log,1,0.322404,0.513211,52,0.000000,1,1,1,1,1
19,0.016550,orderspercustomer_TnI_processed,1,0.322404,0.513211,47,0.707107,1,1,1,1,1
22,0.015043,orderspercustomer_TnI_pw2,1,0.322404,0.513211,49,0.000000,1,1,1,1,1
67,0.000475,orderspercustomer_bi_(10.264285714285698_11.47...,1,0.483979,0.009065,23,0.770417,1,1,1,1,1
5,0.001090,orderspercustomer_bi_(11.4708249496982_12.7638...,1,0.475606,0.019989,14,0.000000,1,1,1,1,1
57,0.008821,orderspercustomer_bi_(13.8482858058315_18.7478...,1,0.422915,0.143209,22,0.708496,1,1,1,1,1
35,0.006260,orderspercustomer_bi_(6.427184466019419_10.264...,0,0.588821,0.148182,39,0.000000,1,1,1,1,1
8,0.011174,spendpercustomers_TnI_log,1,0.351529,0.390438,51,0.000000,1,1,1,1,1
43,0.009614,spendpercustomers_TnI_processed,1,0.351529,0.390438,48,0.707107,1,1,1,1,1
29,0.006696,spendpercustomers_TnI_pw2,1,0.351529,0.390438,50,0.707107,1,1,1,1,1
49,0.003644,spendpercustomers_bi_(1575.24369863014_1767.10...,1,0.450207,0.063666,15,0.707107,1,1,1,1,1
20,0.003715,spendpercustomers_bi_(873.209509803922_1575.24...,0,0.569369,0.082573,38,0.000000,1,1,1,1,1
18,0.000003,spendperorder_TnI_log,0,0.505144,0.189922,46,1.151014,1,1,1,1,1
71,0.000065,spendperorder_TnI_processed,0,0.505144,0.189922,45,1.129397,1,1,1,1,1
48,0.000191,spendperorder_TnI_pw2,0,0.505144,0.189922,44,1.022901,1,1,1,1,1
34,0.000253,spendperorder_bi_(158.066037735849_170.4237958...,0,0.512410,0.005736,21,0.000000,1,1,1,1,1

In [18]:
#Implementing Recursive Feature Elimination 
m.rfe_selection(num_features = 50)

In [19]:
len(m.var_selected)

50

In [20]:
m.var_selected

['DWELLING_TYPE_TnI_processed',
 'DWELLING_TYPE_bi_(-inf_1.0]',
 'AIRLINE_UPGRADERS_N',
 'INCOME_TnI_log',
 'MARITAL_STATUS_bi_(-inf_1.0]',
 'MARITAL_STATUS_TnI_pw2',
 'spendpercustomers_TnI_log',
 'PROFITABILITY_INDEX_TnI_processed',
 'LIFE_EVENT_INDEX_TnI_pw2',
 'BARGAIN_SHOPPERS_N',
 'Online Movie Interest_N',
 'INCOME_TnI_processed',
 'spendperorder_TnI_log',
 'orderspercustomer_TnI_processed',
 'spendpercustomers_bi_(873.209509803922_1575.24369863014]',
 'PRESENCE_OF_CHILDREN_N',
 'orderspercustomer_TnI_pw2',
 'LOR_TnI_pw2',
 'LIFE_EVENT_INDEX_TnI_processed',
 'MOBILITY_TRIGGER_N',
 'PROFITABILITY_INDEX_TnI_pw2',
 'spendpercustomers_TnI_pw2',
 'PROFITABILITY_INDEX_TnI_log',
 'orderspercustomer_bi_(6.427184466019419_10.264285714285698]',
 'Online Music Interest_N',
 'PRESENCE_OF_FINANCE_LOAN_N',
 'Subscribes to Magazines Online_N',
 'Online Savings_N',
 'LOR_bi_(3.0_11.0]',
 'spendpercustomers_TnI_processed',
 'Online Transactor_N',
 'LOYALTY_MEMBERS_N',
 'spendperorder_TnI_pw2',
 'HOME_VALUE_tni_assign',
 'AGE_RANGES_tni_assign',
 'Net Assets_tni_assign',
 'LIFE_EVENT_INDEX_TnI_log',
 'orderspercustomer_TnI_log',
 'LOR_TnI_processed',
 'CREDIT_SCORE_INDEX_tni_assign',
 'VACATION_SPENDERS_N',
 'Online Shopper_N',
 'LOR_bi_(11.0_20.0]',
 'MARITAL_STATUS_TnI_processed',
 'spendperorder_TnI_processed',
 'DWELLING_TYPE_TnI_pw2',
 'PERSONAL_TRAVELER_N',
 'Online Insurance Purchasers_N',
 'LOR_TnI_log',
 'INCOME_TnI_pw2']

In [21]:
#lasso reduction and alpha is the penalty parameter
m.lasso_selection(alpha = 2)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.17420863570799353
            Iterations: 722
            Function evaluations: 722
            Gradient evaluations: 722

In [22]:
m.var_selected

['DWELLING_TYPE_TnI_processed',
 'DWELLING_TYPE_bi_(-inf_1.0]',
 'AIRLINE_UPGRADERS_N',
 'INCOME_TnI_log',
 'MARITAL_STATUS_bi_(-inf_1.0]',
 'MARITAL_STATUS_TnI_pw2',
 'spendpercustomers_TnI_log',
 'PROFITABILITY_INDEX_TnI_processed',
 'LIFE_EVENT_INDEX_TnI_pw2',
 'BARGAIN_SHOPPERS_N',
 'Online Movie Interest_N',
 'INCOME_TnI_processed',
 'spendperorder_TnI_log',
 'orderspercustomer_TnI_processed',
 'spendpercustomers_bi_(873.209509803922_1575.24369863014]',
 'PRESENCE_OF_CHILDREN_N',
 'orderspercustomer_TnI_pw2',
 'LOR_TnI_pw2',
 'LIFE_EVENT_INDEX_TnI_processed',
 'MOBILITY_TRIGGER_N',
 'PROFITABILITY_INDEX_TnI_pw2',
 'spendpercustomers_TnI_pw2',
 'PROFITABILITY_INDEX_TnI_log',
 'orderspercustomer_bi_(6.427184466019419_10.264285714285698]',
 'Online Music Interest_N',
 'PRESENCE_OF_FINANCE_LOAN_N',
 'Subscribes to Magazines Online_N',
 'Online Savings_N',
 'LOR_bi_(3.0_11.0]',
 'spendpercustomers_TnI_processed',
 'Online Transactor_N',
 'LOYALTY_MEMBERS_N',
 'spendperorder_TnI_pw2',
 'HOME_VALUE_tni_assign',
 'AGE_RANGES_tni_assign',
 'Net Assets_tni_assign',
 'LIFE_EVENT_INDEX_TnI_log',
 'orderspercustomer_TnI_log',
 'LOR_TnI_processed',
 'CREDIT_SCORE_INDEX_tni_assign',
 'VACATION_SPENDERS_N',
 'Online Shopper_N',
 'LOR_bi_(11.0_20.0]',
 'MARITAL_STATUS_TnI_processed',
 'spendperorder_TnI_processed',
 'DWELLING_TYPE_TnI_pw2',
 'PERSONAL_TRAVELER_N',
 'Online Insurance Purchasers_N',
 'LOR_TnI_log',
 'INCOME_TnI_pw2']

### Model Fit

In [ ]:
?m.fit

In [23]:
%%time
final_results = m.fit()
final_results['model_descriptor'].sort_values(['importance'], ascending = False)

Train mean response:  0.050078988941548185
Test mean response:  0.04935346286642746
Deviation in response: -1.45%
Wall time: 7.08 s

,variable,estimate,standard_error,t_z_val,p_val,vif,standardized_coeff,importance,corr_dv_direction,corr_model,evaluation
45,spendperorder_TnI_processed,-9.278482e-01,2.883254e-01,-3.218059,1.290611e-03,2.990762e+04,-18.107092,0.242994,0.0,0,0
13,spendperorder_TnI_log,6.719698e+01,2.168109e+01,3.099336,1.939546e-03,7.820833e+03,9.150705,0.122801,0.0,1,0
33,spendperorder_TnI_pw2,1.486360e-03,4.820015e-04,3.083724,2.044271e-03,7.495784e+03,8.552909,0.114778,0.0,1,0
12,INCOME_TnI_processed,4.710271e+00,6.786387e+00,0.694076,4.876343e-01,2.527943e+05,7.397987,0.099280,1.0,1,0
4,INCOME_TnI_log,-2.121538e+01,2.981616e+01,-0.711540,4.767498e-01,6.084601e+04,-3.729081,0.050044,1.0,0,0
50,INCOME_TnI_pw2,-1.228532e-01,1.904838e-01,-0.644953,5.189574e-01,6.624757e+04,-3.512957,0.047143,1.0,0,0
14,orderspercustomer_TnI_processed,7.854620e-01,6.462854e-01,1.215349,2.242332e-01,4.410932e+03,2.688398,0.036078,1.0,1,0
7,spendpercustomers_TnI_log,5.769748e+00,3.318935e+00,1.738434,8.213443e-02,1.320506e+03,2.481751,0.033305,1.0,1,0
38,orderspercustomer_TnI_log,-6.074629e+00,3.957840e+00,-1.534834,1.248245e-01,1.353587e+03,-2.200414,0.029529,1.0,0,0
30,spendpercustomers_TnI_processed,-3.695111e-03,2.925028e-03,-1.263274,2.064908e-01,2.891977e+03,-2.189781,0.029386,1.0,0,0
39,LOR_TnI_processed,3.122118e-01,6.556383e-02,4.761953,1.917285e-06,3.343743e+02,2.113794,0.028367,0.0,1,0
49,LOR_TnI_log,-1.629395e+00,1.453128e-01,-11.213017,3.519870e-29,5.065845e+01,-1.517694,0.020367,0.0,0,0
18,LOR_TnI_pw2,-7.246598e-03,2.310748e-03,-3.136040,1.712458e-03,1.548723e+02,-1.063771,0.014276,0.0,0,0
17,orderspercustomer_TnI_pw2,-1.389354e-02,1.476752e-02,-0.940817,3.467984e-01,1.266168e+03,-1.039275,0.013947,1.0,0,0
1,DWELLING_TYPE_TnI_processed,2.232576e+00,NaN,NaN,NaN,inf,-0.978372,0.013130,1.0,1,0
22,spendpercustomers_TnI_pw2,4.287233e-07,4.262394e-07,1.005827,3.144986e-01,8.041733e+02,0.857909,0.011513,1.0,1,0
8,PROFITABILITY_INDEX_TnI_processed,3.929453e-01,2.271024e-01,1.730256,8.358450e-02,2.617775e+02,0.819413,0.010996,0.0,1,0
19,LIFE_EVENT_INDEX_TnI_processed,-4.523322e-01,7.005450e-01,-0.645686,5.184827e-01,1.904343e+03,-0.797658,0.010704,1.0,0,0
2,DWELLING_TYPE_bi_(-inf_1.0],1.406105e-01,NaN,NaN,NaN,9.007199e+15,-0.797633,0.010704,0.0,1,0
46,DWELLING_TYPE_TnI_pw2,-3.247749e-01,NaN,NaN,NaN,inf,0.774196,0.010390,1.0,0,0
21,PROFITABILITY_INDEX_TnI_pw2,-3.586021e-02,1.576625e-02,-2.274491,2.293646e-02,8.236370e+01,-0.673415,0.009037,0.0,0,0
9,LIFE_EVENT_INDEX_TnI_pw2,2.241243e-02,3.022619e-02,0.741491,4.583960e-01,6.519884e+02,0.515567,0.006919,1.0,1,0
37,LIFE_EVENT_INDEX_TnI_log,1.282697e+00,1.912315e+00,0.670756,5.023759e-01,3.707546e+02,0.388269,0.005210,1.0,1,0
23,PROFITABILITY_INDEX_TnI_log,-3.127954e-01,3.366596e-01,-0.929115,3.528296e-01,6.807634e+01,-0.208346,0.002796,0.0,0,0
31,Online Transactor_N,-4.499153e-01,5.547464e-02,-8.110287,5.050045e-16,1.256256e+00,-0.204589,0.002746,0.0,0,1
36,Net Assets_tni_assign,1.006152e-01,2.870578e-02,3.505049,4.565228e-04,3.973892e+00,0.161623,0.002169,1.0,1,1
29,LOR_bi_(3.0_11.0],3.469022e-01,1.298252e-01,2.672071,7.538463e-03,6.354373e+00,0.157135,0.002109,0.0,1,0
43,LOR_bi_(11.0_20.0],3.054658e-01,2.579876e-01,1.184033,2.364001e-01,1.881499e+01,0.131613,0.001766,0.0,1,0
34,HOME_VALUE_tni_assign,3.805940e-02,1.156368e-02,3.291288,9.972961e-04,1.622029e+00,0.128108,0.001719,1.0,1,1
26,PRESENCE_OF_FINANCE_LOAN_N,3.427248e-01,9.395084e-02,3.647917,2.643755e-04,1.142775e+00,0.123448,0.001657,1.0,1,1
27,Subscribes to Magazines Online_N,-2.510098e-01,5.544262e-02,-4.527380,5.971962e-06,1.433187e+00,-0.123054,0.001651,0.0,0,1
35,AGE_RANGES_tni_assign,5.282909e-02,1.349650e-02,3.914279,9.067474e-05,1.762321e+00,0.118062,0.001584,1.0,1,1
25,Online Music Interest_N,-1.933873e-01,5.853531e-02,-3.303773,9.539319e-04,1.620942e+00,-0.096691,0.001298,0.0,0,1
15,spendpercustomers_bi_(873.209509803922_1575.24...,-1.839176e-01,8.887662e-02,-2.069359,3.851241e-02,3.040466e+00,-0.091305,0.001225,0.0,0,1
3,AIRLINE_UPGRADERS_N,-1.610279e-01,5.265469e-02,-3.058188,2.226798e-03,1.229394e+00,-0.080330,0.001078,0.0,0,1
44,MARITAL_STATUS_TnI_processed,-1.137754e+02,NaN,NaN,NaN,inf,-0.061451,0.000825,1.0,0,0
24,orderspercustomer_bi_(6.427184466019419_10.264...,1.197119e-01,9.609129e-02,1.245814,2.128327e-01,2.998386e+00,0.058623,0.000787,0.0,1,0
40,CREDIT_SCORE_INDEX_tni_assign,3.779614e-02,1.962924e-02,1.925502,5.416658e-02,1.371845e+00,0.055493,0.000745,1.0,1,0
5,MARITAL_STATUS_bi_(-inf_1.0],-4.557214e+01,NaN,NaN,NaN,inf,-0.054139,0.000727,0.0,0,0
41,VACATION_SPENDERS_N,1.040601e-01,6.398229e-02,1.626390,1.038668e-01,1.885098e+00,0.051980,0.000698,0.0,1,0
42,Online Shopper_N,-1.203457e-01,6.775860e-02,-1.776095,7.571723e-02,1.088138e+00,-0.042684,0.000573,1.0,0,0
6,MARITAL_STATUS_TnI_pw2,2.275666e+01,NaN,NaN,NaN,inf,0.041762,0.000560,1.0,1,0
28,Online Savings_N,7.526402e-02,5.522502e-02,1.362861,1.729264e-01,1.310604e+00,0.036145,0.000485,0.0,1,0
32,LOYALTY_MEMBERS_N,-5.661698e-02,6.979427e-02,-0.811198,4.172519e-01,2.048431e+00,-0.026295,0.000353,0.0,0,0
47,PERSONAL_TRAVELER_N,-5.236250e-02,6.734378e-02,-0.777540,4.368401e-01,1.997086e+00,-0.024579,0.000330,0.0,0,0
48,Online Insurance Purchasers_N,5.277851e-02,5.654819e-02,0.933337,3.506461e-01,1.346117e+00,0.024403,0.000327,0.0,1,0
16,PRESENCE_OF_CHILDREN_N,8.708543e-02,1.060420e-01,0.821235,4.115124e-01,1.034333e+00,0.022771,0.000306,1.0,1,0
10,BARGAIN_SHOPPERS_N,6.721625e-02,1.037657e-01,0.647769,5.171342e-01,1.216085e+00,0.022568,0.000303,1.0,1,0
11,Online Movie Interest_N,3.213433e-02,5.752099e-02,0.558654,5.763979e-01,1.560336e+00,0.016027,0.000215,0.0,1,0
20,MOBILITY_TRIGGER_N,1.378155e-02,6.070058e-02,0.227042,8.203914e-01,1.497817e+00,0.005449,0.000073,0.0,1,0
0,intercept,-1.176309e+02,NaN,NaN,NaN,0.000000e+00,0.000000,0.000000,NaN,0,0

### Manual Variable Selection

In [24]:
m.var_selected = [
    'Online Transactor_N',
    'Net Assets_tni_assign',
    'HOME_VALUE_tni_assign',
    'PRESENCE_OF_FINANCE_LOAN_N',
    'Subscribes to Magazines Online_N',
    'AGE_RANGES_tni_assign',
    'Online Music Interest_N',
    'AIRLINE_UPGRADERS_N'
]

### Manual Model Fit

In [25]:
%%time
final_results = m.fit()

Train mean response:  0.050078988941548185
Test mean response:  0.04935346286642746
Deviation in response: -1.45%
Wall time: 821 ms

In [26]:
final_results['model_descriptor'].sort_values(['importance'], ascending = False)

,variable,estimate,standard_error,t_z_val,p_val,vif,standardized_coeff,importance,corr_dv_direction,corr_model,evaluation
3,HOME_VALUE_tni_assign,0.201948,0.011375,17.753104,1.630859e-70,1.146846,0.679757,0.357242,1.0,1,1
6,AGE_RANGES_tni_assign,0.117125,0.011605,10.092982,5.933907e-24,1.328918,0.261750,0.137561,1.0,1,1
4,PRESENCE_OF_FINANCE_LOAN_N,0.708451,0.090988,7.786172,6.907006e-15,1.083452,0.255181,0.134109,1.0,1,1
2,Net Assets_tni_assign,0.145221,0.013899,10.447976,1.496853e-25,1.143759,0.233277,0.122597,1.0,1,1
5,Subscribes to Magazines Online_N,-0.398872,0.047488,-8.399342,4.489884e-17,1.191622,-0.195541,0.102766,0.0,0,1
1,Online Transactor_N,-0.309963,0.049980,-6.201718,5.584992e-10,1.070440,-0.140949,0.074075,0.0,0,1
8,AIRLINE_UPGRADERS_N,-0.222020,0.048097,-4.616144,3.909351e-06,1.131213,-0.110757,0.058208,0.0,0,1
7,Online Music Interest_N,-0.051158,0.049255,-1.038631,2.989762e-01,1.211275,-0.025578,0.013442,0.0,0,0
0,intercept,-6.767639,0.173812,-38.936658,0.000000e+00,0.000000,0.000000,0.000000,NaN,0,0

In [27]:
final_results['model_metric']

{'train_auc': 0.7094311709808687, 'test_auc': 0.7136123962035118}

### Workbook Creation

In [28]:
%%time
m.create_model_playbook("Vyper Demo", "vyper_demo_logisticregression_fulldata.xlsx", oot_data = df_oob, 
                       sort_by_variance = 'desc')

Wall time: 4.29 s

### Scoring a out of time data

In [29]:
df_scored_selected = m.score_oot_data(df_oob)[0]
df_scored_selected.head(20)

,ID,FIRST_NAME,LAST_NAME,ADDRESS,CITY,STATE,ZIP,CREDIT_CARD_REVOLVERS,CREDIT_SCORE_INDEX,INCOME,HOMEOWNER,LOR,MOBILITY_TRIGGER,PRESENCE_OF_CHILDREN,PRESENCE_OF_CREDIT_CARD,PROFITABILITY_INDEX,DWELLING_TYPE,MARITAL_STATUS,NUMBER_OF_CHILDREN,AUTO_INDEX,LIFE_EVENT_INDEX,Childrens Age 0-2,Childrens Age 11-15,Childrens Age 16-17,Childrens Age 3-5,Childrens Age 6-10,Devotional,Reading,Childrens Books,Cooking,Fashion,Interior Decorating,Romance,Baking,Career Advancement Courses,Cigar Smoking,Sweepstakes,Crafts,Cultural/Arts Events,Gardening,Gourmet Foods,DIY,Home Study Courses,Motorcycle Riding,Photography,Quilting,Scrapbooking,Self-Improvement Courses,Sewing/Knitting,Wine,Woodworking,Christian or Gospel,Classical,Country,Jazz,R&B,Rock N Roll,Own a Cat,Own a Dog,Boating/Sailing,Camping/Hiking,Cycling,Fishing,Fitness/Exercise,Golf,Hunting/Shooting,NASCAR,Running,Skiing,Walking for Health,Yoga/Pilates,Casino Gambling,Cruise Ship Vacation,International Travel,Leisure Travel,RV Vacations,Timeshare,Travel within US,Traveler,Interest in Investing,Interest in Mutual Funds,LOYALTY_MEMBERS,PERSONAL_TRAVELER,VACATION_SPENDERS,BARGAIN_SHOPPERS,interest to purchase Medicare Supplement Insurance,interest to purchase Medicare Advantage Plan,Online Shopper,Online Household,Online Insurance Purchasers,Online Savings,Online Movie Interest,spendperorder,orderspercustomer,spendpercustomers,y,PRESENCE_OF_FINANCE_LOAN_N,PRESENCE_OF_FINANCE_LOAN_Y,AGE_RANGES_tni_assign,AGE_RANGES_A,AGE_RANGES_B,AGE_RANGES_C,AGE_RANGES_D,AGE_RANGES_F,AGE_RANGES_G,AGE_RANGES_H,AGE_RANGES_TnImissing,AGE_RANGES_bi_(-inf_1.0],AGE_RANGES_bi_(3.0_4.0],AGE_RANGES_bi_(7.0_inf],AGE_RANGES_bi_(5.0_6.0],AGE_RANGES_bi_(1.0_2.0],AGE_RANGES_bi_(6.0_7.0],HOME_VALUE_tni_assign,HOME_VALUE_A,HOME_VALUE_B,HOME_VALUE_C,HOME_VALUE_D,HOME_VALUE_E,HOME_VALUE_F,HOME_VALUE_G,HOME_VALUE_H,HOME_VALUE_I,HOME_VALUE_J,HOME_VALUE_K,HOME_VALUE_M,HOME_VALUE_O,HOME_VALUE_TnImissing,HOME_VALUE_bi_(7.0_8.0],HOME_VALUE_bi_(10.0_11.0],HOME_VALUE_bi_(13.0_inf],HOME_VALUE_bi_(12.0_13.0],Net Assets_tni_assign,Net Assets_A,Net Assets_B,Net Assets_C,Net Assets_D,Net Assets_E,Net Assets_F,Net Assets_G,Net Assets_TnImissing,Net Assets_bi_(2.0_3.0],Net Assets_bi_(6.0_inf],AIRLINE_UPGRADERS_N,AIRLINE_UPGRADERS_Y,Subscribes to Magazines Online_N,Subscribes to Magazines Online_Y,Online Transactor_N,Online Transactor_Y,Online Music Interest_N,Online Music Interest_Y,y_pred,decile
44933,22881,MICHAEL,DEMSIA,186 WAYNE ST APT 123D,JERSEY CITY,NJ,7302,N,G,8,Y,3.0,Y,N,NaN,1.0,2.0,2.0,NaN,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,Y,NaN,N,N,N,119.476804,11.094025,1325.478648,0,1,0,8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,5,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,0,0.033451,6
58369,217527,SANDI,WERFEL,331 ANCHORAGE DR,WOODBURY,NY,11797,N,G,11,Y,3.0,N,N,NaN,1.0,1.0,1.0,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,N,N,N,N,Y,N,N,Y,144.579826,12.763889,1845.400833,1,1,0,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,7,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,0,1,0.107798,1
27537,135412,JENNIFER,SALEMI,49 DAFFODIL CT,STATEN ISLAND,NY,10312,N,F,9,Y,11.0,N,N,NaN,4.0,1.0,1.0,NaN,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,Y,Y,Y,Y,135.656909,7.373529,1000.270206,0,1,0,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0.007343,10
23143,149276,ERICA,BUDHRAM,10732 110TH ST,SOUTH RICHMOND HILL,NY,11419,N,F,7,Y,11.0,N,N,NaN,5.0,1.0,1.0,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,NaN,N,N,N,114.603266,4.304348,493.292319,0,1,0,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0.022147,8
3205,170035,JASON,SPAIN,9 BERNARDS AVE,BERNARDSVILLE,NJ,7924,N,H,8,Y,6.0,N,N,NaN,2.0,1.0,2.0,NaN,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,Y,Y,Y,N,213.918871,9.358491,2001.957736,0,1,0,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0.006804,10
19631,84793,SUZANNE,ZAHN,PO BOX 353,MANHASSET,NY,11030,N,G,11,Y,20.0,N,N,NaN,4.0,0.0,1.0,NaN,5.0,9.0,NaN,NaN,Y,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,Y,NaN,NaN,NaN,Y,Y,N,N,N,N,Y,Y,N,N,N,169.487995,16.478346,2792.881909,0,0,1,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,5,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,0,1,0,0.023829,7
17317,77876,JERI,HARRISON,155 W 20TH ST APT 3J,NEW YORK,NY,10011,N,H,9,N,6.0,N,N,Y,2.0,2.0,2.0,0.0,3.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,Y,N,N,Y,141.705326,11.779804,1669.260994,0,1,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,5,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,1,0,0.072781,3
42176,89169,JAMES,RENTON,202 W 98TH ST APT 4B,NEW YORK,NY,10025,N,F,7,N,3.0,Y,N,NaN,5.0,2.0,2.0,NaN,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,NaN,N,Y,Y,136.758138,13.848286,1893.865779,0,1,0,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0.056617,4
34431,66617,ROBERT,RHOADES,11 TREETOP LN,PLEASANTVILLE,NY,10570,N,H,11,Y,20.0,N,N,NaN,1.0,5.0,1.0,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,N,N,N,Y,Y,N,N,N,168.262130,14.996815,2523.396083,0,1,0,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,6,0,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,0.037043,6
42046,184714,EUGENIA,PIFLAKS,18 DELAWARE ST,HUNTINGTON,NY,11743,N,H,11,N,6.0,N,N,NaN,5.0,1.0,1.0,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,N,N,N,N,N,N,N,Y,Y,N,Y,187.689296,7.875000,1478.053208,0,1,0,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0.050676,5
47540,34855,RITA,HEFTLER,26910 GRAND CENTRAL PKWY PH C,FLORAL PARK,NY,11005,N,H,7,Y,11.0,N,N,NaN,1.0,2.0,2.0,NaN,8.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,Y,Y,N,N,N,120.477976,10.509091,1266.114000,0,1,0,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,5,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,0.014329,9
56915,128931,ELISA,VALERIO,950 WOODYCREST AVE APT 28B,BRONX,NY,10452,Y,C,8,N,11.0,N,N,NaN,9.0,2.0,1.0,NaN,1.0,1.0,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,Y,N,N,N,Y,N,N,Y,115.614365,6.176471,714.088725,0,1,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0.047927,5
12825,196393,LAURIE,GAMA,325 WASHINGTON AVE,AVON BY THE SEA,NJ,7717,N,G,11,Y,2.0,Y,N,NaN,2.0,1.0,1.0,NaN,9.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,N,N,N,N,Y,N,N,Y,175.651402,6.114286,1073.982857,0,1,0,8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,5,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,0,0,1,0.110985,1
49253,4438,ELISA,CARULLI,81 ATLAS AVE UNIT A,MALVERNE,NY,11565,N,G,9,Y,3.0,N,N,NaN,3.0,2.0,1.0,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,Y,Y,Y,NaN,NaN,NaN,NaN,Y,NaN,Y,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,NaN,NaN,Y,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,Y,Y,Y,Y,Y,Y,Y,Y,N,N,N,Y,N,Y,Y,147.620585,9.913580,1463.448519,0,1,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,6,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,1,0,0.013629,9
57269,125390,HARRY,FOTIADIS,159 PARK AVE,EASTCHESTER,NY,10709,N,G,11,Y,20.0,N,Y,Y,1.0,1.0,1.0,1.0,9.0,9.0,NaN,NaN,Y,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,Y,Y,Y,N,N,N,N,Y,N,N,Y,160.354753,14.649635,2349.138613,0,0,1,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,6,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0.045793,5
63894,134879,JULIAN,GIAT,214 N 11TH ST APT 5N,BROOKLYN,NY,11211,N,G,7,Y,6.0,N,N,Y,1.0,5.0,2.0,0.0,7.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,Y,Y,Y,Y,136.453100,8.083804,1103.060132,0,1,0,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0.072762,3
46014,158220,DAVA,HUBER,212 CARROLL ST,BROOKLYN,NY,11231,N,G,8,N,3.0,Y,N,Y,5.0,2.0,2.0,0.0,5.0,7.0,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,Y,N,Y,Y,160.358317,9.928976,1592.193850,0,1,0,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0.069710,3
30855,34659,BELLA,SCHWARTZ,1337 E 24TH ST,BROOKLYN,NY,11210,N,H,7,Y,20.0,N,N,Y,1.0,1.0,1.0,0.0,5.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,Y,Y,Y,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,Y,Y,Y,NaN,NaN,Y,Y,Y,Y,N,Y,Y,N,N,N,N,NaN,N,N,N,132.685281,7.140655,947.459827,0,1,0,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,7,0,0,0,0,0,0,1,0,0,0,0,1,0,1,1,0,1,0,0.090303,2
49185,185402,SHANNON,BEATTY,616 E 18TH ST APT 5A,BROOKLYN,NY,11226,N,H,8,N,11.0,N,N,NaN,6.0,2.0,2.0,NaN,3.0,6.0,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,NaN,Y,N,Y,140.244193,7.724909,1083.373670,0,1,0,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0.050676,5
6366,158150,ANITA,HALVATZIS,15415 POWELLS COVE BLVD,WHITESTONE,NY,11357,N,G,10,Y,20.0,N,N,NaN,1.0,1.0,3.0,NaN,8.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,N,N,N,N,Y,N,N,N,152.486938,10.863806,1656.588507,0,1,0,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,7,0,0,0,0,0,0,1,0,0,0,1,0,1,0,1,0,1,0,0.050650,5

### Generate Python Code

In [30]:
m.generate_python_code?

In [31]:
print(m.generate_python_code(in_df_name = 'df', out_df_name = 'df_out', y_name = 'y_pred'))

df_out = df.copy()

df_out['AGE_RANGES'] = df_out['AGE_RANGES'].fillna('TnImissing')
df_out['AGE_RANGES_tni_assign'] = df_out['AGE_RANGES'].replace({'G': 1, 'F': 2, 'A': 3, 'H': 4, 'D': 5, 'C': 6, 'B': 7, 'TnImissing': 8})
df_out = pd.get_dummies(df_out, columns=['AGE_RANGES'])
for col in [8, 10]:
    if col in df_out.columns:
        df_out.drop(columns=col, inplace=True)
og_tni_dummies = ['AGE_RANGES_bi_(-inf_1.0]', 'AGE_RANGES_bi_(3.0_4.0]', 'AGE_RANGES_bi_(7.0_inf]', 'AGE_RANGES_bi_(5.0_6.0]', 'AGE_RANGES_bi_(1.0_2.0]', 'AGE_RANGES_bi_(6.0_7.0]']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out['AIRLINE_UPGRADERS'] = df_out['AIRLINE_UPGRADERS'].fillna('TnImissing')
df_out = pd.get_dummies(df_out, columns=['AIRLINE_UPGRADERS'])
og_tni_dummies = ['AIRLINE_UPGRADERS_N', 'AIRLINE_UPGRADERS_Y']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out['Online Music Interest'] = df_out['Online Music Interest'].fillna('TnImissing')
df_out = pd.get_dummies(df_out, columns=['Online Music Interest'])
og_tni_dummies = ['Online Music Interest_N', 'Online Music Interest_Y']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out['HOME_VALUE'] = df_out['HOME_VALUE'].fillna('TnImissing')
df_out['HOME_VALUE_tni_assign'] = df_out['HOME_VALUE'].replace({'E': 1, 'B': 2, 'J': 3, 'I': 4, 'G': 5, 'C': 6, 'A': 7, 'K': 8, 'F': 9, 'H': 10, 'M': 11, 'D': 12, 'O': 13, 'TnImissing': 14})
df_out = pd.get_dummies(df_out, columns=['HOME_VALUE'])
for col in [6, 7, 9, 12, 13, 14, 15, 16, 18, 19]:
    if col in df_out.columns:
        df_out.drop(columns=col, inplace=True)
og_tni_dummies = ['HOME_VALUE_bi_(7.0_8.0]', 'HOME_VALUE_bi_(10.0_11.0]', 'HOME_VALUE_bi_(13.0_inf]', 'HOME_VALUE_bi_(12.0_13.0]']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out['Net Assets'] = df_out['Net Assets'].fillna('TnImissing')
df_out['Net Assets_tni_assign'] = df_out['Net Assets'].replace({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'TnImissing': 8})
df_out = pd.get_dummies(df_out, columns=['Net Assets'])
for col in [6, 7, 9, 10, 11]:
    if col in df_out.columns:
        df_out.drop(columns=col, inplace=True)
og_tni_dummies = ['Net Assets_bi_(2.0_3.0]', 'Net Assets_bi_(6.0_inf]']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out['Online Transactor'] = df_out['Online Transactor'].fillna('TnImissing')
df_out = pd.get_dummies(df_out, columns=['Online Transactor'])
og_tni_dummies = ['Online Transactor_N', 'Online Transactor_Y']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out['PRESENCE_OF_FINANCE_LOAN'] = df_out['PRESENCE_OF_FINANCE_LOAN'].fillna('TnImissing')
df_out = pd.get_dummies(df_out, columns=['PRESENCE_OF_FINANCE_LOAN'])
og_tni_dummies = ['PRESENCE_OF_FINANCE_LOAN_N', 'PRESENCE_OF_FINANCE_LOAN_Y']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out['Subscribes to Magazines Online'] = df_out['Subscribes to Magazines Online'].fillna('TnImissing')
df_out = pd.get_dummies(df_out, columns=['Subscribes to Magazines Online'])
og_tni_dummies = ['Subscribes to Magazines Online_N', 'Subscribes to Magazines Online_Y']
for og in og_tni_dummies:
    if og not in df_out.columns:
        df_out[og] = 0

df_out = df_out[['Online Transactor_N', 'Net Assets_tni_assign', 'HOME_VALUE_tni_assign', 'PRESENCE_OF_FINANCE_LOAN_N', 'Subscribes to Magazines Online_N', 'AGE_RANGES_tni_assign', 'Online Music Interest_N', 'AIRLINE_UPGRADERS_N']]

df_out['y_pred'] = 1 / (1 + np.exp(-1.0 * (-6.767639432350379 + (-0.3099626285655962 * df_out['Online Transactor_N']) + (0.1452213912296822 * df_out['Net Assets_tni_assign']) + (0.2019477874940289 * df_out['HOME_VALUE_tni_assign']) + (0.7084512845001576 * df_out['PRESENCE_OF_FINANCE_LOAN_N']) + (-0.39887189392721545 * df_out['Subscribes to Magazines Online_N']) + (0.11712518586420165 * df_out['AGE_RANGES_tni_assign']) + (-0.051158074139477296 * df_out['Online Music Interest_N']) + (-0.2220204655485797 * df_out['AIRLINE_UPGRADERS_N']))))

### Pickle

In [32]:
m.clear_data()

In [33]:
#Dumping the model
import joblib
filename = 'final_log_model.pkl'
joblib.dump(m,open(filename, 'wb'))

In [34]:
#loading the saved model object
loaded_model = joblib.load(open(filename, 'rb'))
df_scored_selected = loaded_model.score_oot_data(df_oob)[0]
df_scored_selected.head(5)

,ID,FIRST_NAME,LAST_NAME,ADDRESS,CITY,STATE,ZIP,CREDIT_CARD_REVOLVERS,CREDIT_SCORE_INDEX,INCOME,HOMEOWNER,LOR,MOBILITY_TRIGGER,PRESENCE_OF_CHILDREN,PRESENCE_OF_CREDIT_CARD,PROFITABILITY_INDEX,DWELLING_TYPE,MARITAL_STATUS,NUMBER_OF_CHILDREN,AUTO_INDEX,LIFE_EVENT_INDEX,Childrens Age 0-2,Childrens Age 11-15,Childrens Age 16-17,Childrens Age 3-5,Childrens Age 6-10,Devotional,Reading,Childrens Books,Cooking,Fashion,Interior Decorating,Romance,Baking,Career Advancement Courses,Cigar Smoking,Sweepstakes,Crafts,Cultural/Arts Events,Gardening,Gourmet Foods,DIY,Home Study Courses,Motorcycle Riding,Photography,Quilting,Scrapbooking,Self-Improvement Courses,Sewing/Knitting,Wine,Woodworking,Christian or Gospel,Classical,Country,Jazz,R&B,Rock N Roll,Own a Cat,Own a Dog,Boating/Sailing,Camping/Hiking,Cycling,Fishing,Fitness/Exercise,Golf,Hunting/Shooting,NASCAR,Running,Skiing,Walking for Health,Yoga/Pilates,Casino Gambling,Cruise Ship Vacation,International Travel,Leisure Travel,RV Vacations,Timeshare,Travel within US,Traveler,Interest in Investing,Interest in Mutual Funds,LOYALTY_MEMBERS,PERSONAL_TRAVELER,VACATION_SPENDERS,BARGAIN_SHOPPERS,interest to purchase Medicare Supplement Insurance,interest to purchase Medicare Advantage Plan,Online Shopper,Online Household,Online Insurance Purchasers,Online Savings,Online Movie Interest,spendperorder,orderspercustomer,spendpercustomers,y,PRESENCE_OF_FINANCE_LOAN_N,PRESENCE_OF_FINANCE_LOAN_Y,AGE_RANGES_tni_assign,AGE_RANGES_A,AGE_RANGES_B,AGE_RANGES_C,AGE_RANGES_D,AGE_RANGES_F,AGE_RANGES_G,AGE_RANGES_H,AGE_RANGES_TnImissing,AGE_RANGES_bi_(-inf_1.0],AGE_RANGES_bi_(3.0_4.0],AGE_RANGES_bi_(7.0_inf],AGE_RANGES_bi_(5.0_6.0],AGE_RANGES_bi_(1.0_2.0],AGE_RANGES_bi_(6.0_7.0],HOME_VALUE_tni_assign,HOME_VALUE_A,HOME_VALUE_B,HOME_VALUE_C,HOME_VALUE_D,HOME_VALUE_E,HOME_VALUE_F,HOME_VALUE_G,HOME_VALUE_H,HOME_VALUE_I,HOME_VALUE_J,HOME_VALUE_K,HOME_VALUE_M,HOME_VALUE_O,HOME_VALUE_TnImissing,HOME_VALUE_bi_(7.0_8.0],HOME_VALUE_bi_(10.0_11.0],HOME_VALUE_bi_(13.0_inf],HOME_VALUE_bi_(12.0_13.0],Net Assets_tni_assign,Net Assets_A,Net Assets_B,Net Assets_C,Net Assets_D,Net Assets_E,Net Assets_F,Net Assets_G,Net Assets_TnImissing,Net Assets_bi_(2.0_3.0],Net Assets_bi_(6.0_inf],AIRLINE_UPGRADERS_N,AIRLINE_UPGRADERS_Y,Subscribes to Magazines Online_N,Subscribes to Magazines Online_Y,Online Transactor_N,Online Transactor_Y,Online Music Interest_N,Online Music Interest_Y,y_pred,decile
44933,22881,MICHAEL,DEMSIA,186 WAYNE ST APT 123D,JERSEY CITY,NJ,7302,N,G,8,Y,3.0,Y,N,NaN,1.0,2.0,2.0,NaN,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,Y,NaN,N,N,N,119.476804,11.094025,1325.478648,0,1,0,8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,5,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,0,0.033451,6
58369,217527,SANDI,WERFEL,331 ANCHORAGE DR,WOODBURY,NY,11797,N,G,11,Y,3.0,N,N,NaN,1.0,1.0,1.0,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,N,N,N,N,Y,N,N,Y,144.579826,12.763889,1845.400833,1,1,0,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,7,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,0,1,0.107798,1
27537,135412,JENNIFER,SALEMI,49 DAFFODIL CT,STATEN ISLAND,NY,10312,N,F,9,Y,11.0,N,N,NaN,4.0,1.0,1.0,NaN,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,Y,Y,Y,Y,135.656909,7.373529,1000.270206,0,1,0,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0.007343,10
23143,149276,ERICA,BUDHRAM,10732 110TH ST,SOUTH RICHMOND HILL,NY,11419,N,F,7,Y,11.0,N,N,NaN,5.0,1.0,1.0,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,NaN,N,N,N,114.603266,4.304348,493.292319,0,1,0,4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0.022147,8
3205,170035,JASON,SPAIN,9 BERNARDS AVE,BERNARDSVILLE,NJ,7924,N,H,8,Y,6.0,N,N,NaN,2.0,1.0,2.0,NaN,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,Y,Y,Y,N,213.918871,9.358491,2001.957736,0,1,0,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0.006804,10